### ISSUE TITLE
@EndText ... EndText string literal blocks

### ISSUE THREAD

**Issue by andrewransom** [GwennKoi/vscode-lpc-lang#2] opened 2019-10-09 19:39 UTC
Thanks for this extension! I lack the time to delve into the details of how it all works so thought I'd ask here: Is it feasible to build in support for multi-line string literal blocks?

Example:
```
    set("long",@EndText
    This is a really long description that spans multiple lines and
may have some single-quote apostrophes in it. It's my hope that
those apostrophes can be set to be included in this block of text!
EndText
    );
```

This is the convention we use in our system frequently. But the entire syntax highlighting
gets broken by those `'`s.

**Comment by GwennKoi** [comment] 2019-10-09 19:56
First off, what's your mud?

Secondly, I've had the same problem and have looked into it with no success yet.

The way to do all of this properly is to write a language server which would run in the background and do all of the complicated parsing. Language servers enable a lot of other really cool features. The problem is that I don't really have the time to create one. It's on a very, very long personal todo list.

I'll take a look at it sometime soon to see if I can accomplish it in the current parser rules, but I wouldn't hold my breath.

**Comment by andrewransom** [comment] 2019-10-13 23:18
The Two Towers for me.  :)

My typical workaround is to just disable `'` as a string-delimiter in the syntax definition - that solves most problems. If you're able to come up with something better, great. No worries. otherwise. Thanks for the response.

**Comment by gesslar** [comment] 2019-12-31 00:12
@andrewransom This is how I get around it, and I've had to do this in a number of editors:

```
set("long", @text
   This is the long description. Isn't it fabulous??
text //'
); 
```

**Comment by GwennKoi** [comment] 2022-09-16 18:23
After doing a lot of research, the problem is really hard to fix. The main issue is that this feature in the language itself is a hack and wasn't implemented via good syntax parsing. I've talked to the primary maintainer of FluffOS and they have the exact same issue with that syntax in the driver itself and have to hack around it there.

As always, I am still looking for help on how to handle this particular issue.

**Comment by GwennKoi** [comment] 2023-05-27 19:54
This was fixed in the last patch.

**Closed as completed by GwennKoi** 2023-05-27 19:54 UTC
Labels: bug, help wanted
